### ISSUE TITLE
Demo throws TypeError

### ISSUE THREAD

**Issue by BernhardKonrad** [cytoscape/cytoscape.js-popper#19]
The demo shows a graph, but not everything seems to be working as intended. Console shows

TypeError: Popper is undefined  cytoscape-popper.js:319:5
TypeError: cy.nodes(...)[0].popper is not a function  cytoscape.js-popper:260:17

**Comment by maxkfranz** [comment]
The extension hasn't been published yet.  Clone the code and run locally

**Comment by amadeuspagel** [comment]
Is this still true? I get the same error.
