### ISSUE TITLE
popper not hiding with the rest of the graph when panned out of view

### ISSUE THREAD

**Issue by jmazzitelli** [cytoscape/cytoscape.js-popper#21]
Was wondering if this is a problem in the cy-popper integration, or if there is some setting I'm missing.

Here's the problem - the popper icon (the lightning bolt "badge" on each node) seems to have a different z-index as the graph - notice how the popper isn't hidden like the rest of the graph when panned out of the viewing area.

![large](https://user-images.githubusercontent.com/2029470/38624957-5ab73510-3d77-11e8-8699-582fccf2c59c.gif)

Here's a snippet of the code:
```
const div = document.createElement('div');
div.className = 'glyphicon glyphicon-flash';
document.getElementById('cy')!.appendChild(div); // tried document.body.appendChild() - no difference
const popper = cyNode.popper({
   content: target => div,
   ... and the rest ...
```

This is the Kiali UI - a front end for Istio. The actual code right now is here: https://github.com/jmazzitelli/kiali-ui/blob/popper/src/components/CytoscapeLayout/graphs/GraphBadge.ts#L20-L69

**Comment by maxkfranz** [comment]
Yes, you'll have to configure the Popper options appropriately for the behaviour you want.  See the Popper docs: https://popper.js.org/popper-documentation.html

This extension is just a wrapper and so it uses the default Popper options by default.

**Comment by jmazzitelli** [comment]
i worked around this. it isn't a bug.
