### ISSUE TITLE
only first popper visible when hideOnClick: true 

### ISSUE THREAD

**Issue by gokhanckgz** [cytoscape/cytoscape.js-popper#25]
I'm create popper with tippy.js using this code

```
let node = cy.getElementById(nextProps.selectedNode);
let tip = MakeTippy(node,nextProps.selectedNode);
tip.show();
//Meteor.setTimeout(function() {
//    tip.hide();
// }, 1500); 
```

MakeTippy() is the same as MakeTippy() function in "demo-tippy.html" file.
When `hideOnClick: true` , only first popper occurs in canvas. After first popper disappears, next ones not occur in canvas.

After the first popper, poppers occur with div which has some properties at below

> class="tippy-tooltip " and "data-state="hidden"

when change this data-state to visible on devtools , poppers became visible.

---

Also when i change "hideOnClick: false" and comment out this line;

`
//Meteor.setTimeout(function() { tip.hide(); }, 1500); 
`
I can see new poppers after old ones hide.

**Comment by maxkfranz** [comment]
`hideOnClick` makes no sense for a non-DOM reference object.
