### ISSUE TITLE
Exporting graphs with popper with cy.png() or cy.jpg() doesn't return the popper-divs

### ISSUE THREAD

**Issue by steevokovsky** [cytoscape/cytoscape.js-popper#27]
### Issue type
New feature
### Environment info
Chrome, Firefox, IE
### Cytoscape.js, Browser, Node.js  version 
latest
### Current behaviour
Exporting a graph with cytoscape-popper divs inside just exports the nodes and edges without the poppers
### Desired behaviour
Exporting a graph with cy.png() or cy.jpg() exports the nodes/edges/labels and popper-divs
### Minimum steps to reproduce
Just build a graph with popper inside and try to export that graph as an image.
[Codepen example](https://codepen.io/steevokovsky/pen/pxQYad)

**Comment by maxkfranz** [comment]
Cytoscape can't export arbitrary DOM objects outside of the graph.
