### ISSUE TITLE
Popper inside a cytoscape node

### ISSUE THREAD

**Issue by klysak** [cytoscape/cytoscape.js-popper#28]
Is it possible to place the popper inside the node? I want to customize cytoscape nodes by the HTML overlay. I think that Popper.js is good solution for it. But how can i do that?

**Comment by maxkfranz** [comment]
No, that isn't a feature of Popper.  See the docs:   https://popper.js.org/popper-documentation.html#Popper

This extension is just wrapper for Popper.js.  If you have questions or feature requests, go to that project's page: https://github.com/FezVrasta/popper.js/

**Comment by maxkfranz** [comment]
See also https://github.com/FezVrasta/popper.js/pull/530
