### ISSUE TITLE
Update Tippy example for v5

### ISSUE THREAD

**Issue by maroneze** [cytoscape/cytoscape.js-popper#31]
The v5 release of Tippy no longer accepts "plain objects", so the example with `popperRef` results in:

    tippy() was passed a plain object which is no longer supported as an argument.

It would be great if the example could be updated to work with Tippy v5 (assuming it is still possible).

(Accessorily, I hope this issue will help others when they encounter the above error message; it took me a while to realize it was due to the new Tippy release, and not something else in my build.)

**Comment by maxkfranz** [comment]
For this usecase you must use a `popperRef`.  So if Tippy 5 doesn't accept that, then you should contact the author of Tippy.

**Comment by maroneze** [comment]
Ok, I will do that, thanks.

**Comment by hope4555** [comment]
happens to me even when using a ref

**Comment by rosnaib11** [comment]
@maxkfranz do you have example how to do that?
