### ISSUE TITLE
Issue while adding tooltip on node using popper extensions

### ISSUE THREAD

**Issue by shwetadatascience** [cytoscape/cytoscape.js-popper#82]
![image](https://github.com/cytoscape/cytoscape.js-popper/assets/114903039/40d088d1-d633-4409-afe9-2265bdd33602)

I want to achieve a tooltip pop-up when hovering over a node using the Cytoscape library and its extensions in angular framework. I have attempted this using various options, including qtip function , cytopropper.js, and the tippy plugin. However, I keep encountering the same exception that states, '**The following property does not exist in nodesingular.**'" .please help me out here @kozo2 @keiono @mes5k

**Comment by maxkfranz** [comment]
This extension isn’t written in TS, so you’ll have to raise this in DefinitelyTyped and/or your own project’s build setup.

**Comment by shwetadatascience** [comment]
Thanks @maxkfranz for your quick response.
